=== ankittiwari0105/ankit-ericsson-boot-camp-Jan2015/sef-core/src/main/resources/META-INF/sef-core/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (section+)>
<!ELEMENT section (property+, router*)>
<!ELEMENT property EMPTY>
<!ELEMENT router (ranges, values)>
<!ELEMENT ranges (range+)>
<!ELEMENT values (value+)>
<!ELEMENT range EMPTY>

<!ATTLIST section
	id 			ID 		#REQUIRED
	description	CDATA 	#REQUIRED
>

<!ATTLIST property
	key CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ATTLIST range
	start CDATA #REQUIRED
	end   CDATA #REQUIRED
	value IDREF #REQURED
>

<!ATTLIST value
	id		ID		#REQURIED
	sdpId 	CDATA	#REQUIRED
	siteId 	CDATA 	#REQUIRED
>

=== ankittiwari0105/ankit-ericsson-boot-camp-Jan2015/sef-core/src/main/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com)-->
<!DOCTYPE config SYSTEM "config.dtd">
<config>
	<section id="GLOBAL" description="global configuration properties">
		<property key="dateFormat" value="yyyy-MM-dd HH:mm:ss.SSS" />
		<property key="milliSecMultiplier" value="86400000" />
		<property key="subscriberNumberNAI" value="1" />
		<property key="preActivePeriod" value="365" />
		<property key="gracePeriod" value="271" />
		<property key="InGTAddress" value="639180001285"/>
		<property key="minDateTimeExtension" value="1" />
		<property key="defaultServiceClass" value="200" />
	</section>
	<section id="GLOBAL_walletMapping" description="smart wallet mapping">
				<property key="1001" value="OnPeakAccountID" />
				<property key="1002" value="RwdMocTri" />
				<property key="1003" value="BucketMocOn" />
				<property key="1004" value="BucketMocSun" />
				<property key="1005" value="BucketMocTri" />
				<property key="1006" value="BucketMocGbl" />
				<property key="1007" value="BucketMocGblInt" />
				<property key="1008" value="BucketMocInt" />
				<property key="1009" value="BucketRoamMoc" />
				<property key="1010" value="BucketIntlS3Moc" />
				<property key="1011" value="CallAllBucketMoc" />
				<property key="1012" value="BucketTokMoc" />
				<property key="1013" value="BucketArawMoc" />
				<property key="1014" value="BucketTkTpdMoc" />
				<property key="1015" value="BucketMocTriCc" />
				<property key="1051" value="RwdSmsGbl" />
				<property key="1052" value="BucketSmsOn" />
				<property key="1053" value="BucketSmsTri" />
				<property key="1054" value="BucketSmsGbl" />
				<property key="1055" value="BucketSmsInt" />
				<property key="1056" value="BucketSmsRoam" />
				<property key="1057" value="BucketIntlS4Sms" />
				<property key="1058" value="BucketTkTpdSms" />
				<property key="1059" value="BucketKamusTxtSms" />
				<property key="1060" value="DailyCapSms" />
				<property key="1061" value="AllTxtBcktSmsGbl" />
				<property key="1101" value="ConsWalletAcc" />
				<property key="1102" value="BucketIntlS1Cbo" />
				<property key="1103" value="BucketIntlS2Cbo" />
				<property key="1104" value="BucketIntlCombo" />
				<property key="1105" value="FlexiBckAcc" />
				<property key="1141" value="DataVolFbc" />
				<property key="1142" value="DataMinFbc" />
				<property key="1143" value="DataArawFbc" />
				<property key="1144" value="RwdVolDataFbc" />
				<property key="1145" value="ComDataFbc" />
				<property key="1146" value="EmailDataFbc" />
				<property key="1147" value="GamesDataFbc" />
				<property key="1148" value="IMDataFbc" />
				<property key="1149" value="AudioStreamFbc" />
				<property key="1150" value="VideoDataFbc" />
				<property key="1151" value="SnsDataFbc" />
				<property key="1152" value="SnsData2Fbc" />
				<property key="1153" value="1030DataFbc" />
				<property key="1154" value="1030AutoFbc" />
				<property key="1155" value="BucketIM6VolFbc " />
				<property key="1241" value="UnivWalletAcc" />
				<property key="2001" value="UnliMocOnCtl" />
				<property key="2002" value="UnliMocTriCtl" />
				<property key="2003" value="UnliMocGblCtl" />
				<property key="2015" value="Katok10" />
				<property key="2016" value="Katok15" />
				<property key="2017" value="KatokAtTex25" />
				<property key="2018" value="KatokAtTex35" />
				<property key="2019" value="KatokSubGrace" />
				<property key="2101" value="UnliSmsOnCtl" />
				<property key="2102" value="UnliSmsTriCtl" />
				<property key="2103" value="UnliSmsGblCtl" />
				<property key="2104" value="UnliAccessSmsCtl" />
				<property key="2301" value="SnsDataFbcCtl" />
				<property key="2302" value="IMDataFbcCtl" />
				<property key="2303" value="ComDataFbcCtl" />
				<property key="2304" value="EmailDataFbcCtl" />
				<property key="2305" value="GamesDataFbcCtl" />
				<property key="2306" value="AudioStreamFbcCtl" />
				<property key="2307" value="VideoDataFbcCtl" />
				<property key="2308" value="LTEUnliSurfFbc" />
				<property key="2309" value="UnliSurfFbcCtl" />
				<property key="2310" value="UnliSurfFbcCtlRen" />
				<property key="2311" value="UnliThroFbcCtl" />
				<property key="2312" value="BrwsThroFbc" />
				<property key="2313" value="BBDataFbcCtl" />
				<property key="2314" value="RoamFbcCtl" />
				<property key="2315" value="UnliKonekFbcCtl" />
				<property key="2316" value="SnsData2FbcCtl" />
				<property key="2317" value="IMData2FbcCtl" />
				<property key="2318" value="UnliNxbFbcCtl" />
				<property key="2319" value="UnliEmail1FbcCtl" />
				<property key="2320" value="UnliIM2FbcCtl" />
				<property key="2321" value="UnliPhoto1FbcCtl" />
				<property key="2322" value="UnliSns1FbcCtl" />
				<property key="2323" value="UnliBoost1FbcCtl" />
				<property key="2324" value="UnliIM1FbcCtl" />
				<property key="2325" value="UnliBrws1FbcCtl" />
				<property key="2326" value="UnliSns2FbcCtl" />
	</section>
	<section id="GLOBAL_welcomePackMapping" description="welcome pack mapping">
			<property key="initialSC" value="200" />
					<property key="wpStdP1" value="1001" />
					<property key="P1" value="1001" />
					<property key="wpPromoP0" value="1002" />
					<property key="P0" value="1002" />
					<property key="wpPromoP1" value="1003" />
					<property key="P1.0" value="1003" />
					<property key="wpPromoP2" value="1004" />
					<property key="P2" value="1004" />
					<property key="wpPromoP20" value="1005" />
					<property key="P20" value="1005" />
					<property key="wpPromoP21" value="1006" />
					<property key="P21" value="1006" />
					<property key="wpPromoP25" value="1007" />
					<property key="P25" value="1007" />
					<property key="wpPromoP30" value="1008" />
					<property key="P30" value="1008" />
					<property key="wpPromoP31" value="1009" />
					<property key="P31" value="1009" />
					<property key="wpPromoP50" value="1010" />
					<property key="P50" value="1010" />
					<property key="wpPromoP101" value="1011" />
					<property key="P101" value="1011" />
					<property key="wpPromoP115" value="1012" />
					<property key="P115" value="1012" />
					<property key="wpPromoP300" value="1013" />
					<property key="P300" value="1013" />
					<property key="wpPromoP999" value="1014" />
					<property key="P999" value="1014" />
					<property key="wpTakaTak" value="1015" />
	</section>
	<section id="GLOBAL_callinguserCredantials" description="calling circle user credentials">
		<property key="ecsd" value="ecsd@oc"/>
	</section>
	<section id="GLOBAL_tagging" description="Subscriber Tagging details" >
		<property key="0" value="NOTAG" />
					<property key="1" value="FORCEDDELETION" />
					<property key="2" value="BANNED" />
					<property key="3" value="BARREDIRM" />
					<property key="4" value="BARREDOTHER" />
					<property key="5" value="SPECIALFRAUD" />
					<property key="6" value="ACTIVATIONFLAG" />
					<property key="7" value="RECYCLE" />
	</section>
	
	
</config>
